### ISSUE TITLE
[EPIC] Matt Standards and PoCs

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#100]
- [x] NFT Standards Call x 2
- [x] NFT Nail down approvals callback
- [x] NFT Start talking markets
- [x] FTs & purchasing NFTs on market
