### ISSUE TITLE
[EPIC] Matt Meta

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#101]
- [x] Define epic rollups for sprint planning
- [x] HR, 1-1s, settling in with the team
- [x] Sprint planning understood
