### ISSUE TITLE
[Epic] Launch Pluminite to the world!

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#107]
# Proposal for: Launching Pluminite to the World

## What is this? 
- Pluminite is the Epic I worked on here: https://github.com/near/devrel/issues/43. It's an NFT marketplace that is open source to encourage devs to contribute to it, and thus get them more familiar with working with NEAR.
With this Epic, I will successfully launch it to the world and wrap up anything open ended hanging from it, as well as track it's success !

## Who needs to be involved?
- @nearlyalmonds @crasskitty @TiffanyGYJ  possibly marketing?

## Tasks to complete (can return to [x] these)
- [ ] post Pluminite on Product Hunt in all it's finished glory
- [ ] Work with marketing to promote it
- [ ] Work with @TiffanyGYJ to track the analytics of how its doing
- [ ] finalize how open source contributions will be assessed and added to the project. 
- [ ] wrap up any other open ended questions.

## What t-shirt size is this? (range: multi-spint to 1 hour)
large

## What priority is this?
- P2 (Important: known docs, feature requests, or known bugs)

**Comment by TiffanyGYJ** [comment]
Yes! Looking forward to this!

**Comment by crasskitty** [comment]
blocked until we have a working product, looks like roughly 2 weeks from today (fingers crossed)
