### ISSUE TITLE
[EPIC] Open Sourcerers specific Bounty Program

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#108]
# Proposal for: Open Sourcerers specific Bounty Program

## What is this? 
- We need a way to let people interested in working with the Open Sourcerers that there is work we need done, and we need a way to distribute this information and quickly get people to pick up the work. 

## Who needs to be involved?
- @cameron-NEAR @jlwaugh @crasskitty @waverlymaven 

## Tasks to complete
- [ ] Talk to Sonja and @waverlymaven to set up a DevRel LLC 
- [ ] claim a spot on sputnik.fund
- [ ] build a chat channel where people can get updates
- [ ] set up a bot or automation or solution to ping them of new bounties on sputnik.fund
- [ ] have a way for them to claim the work with an established deadline 
- [ ] Get funded from NF for giving out bounties

## What t-shirt size is this? (range: multi-spint to 1 hour)
large

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by crasskitty** [comment]
I named this as a P1, because right now we don't have a place specifically for the Dev Rel team to coordinate these efforts, which means that when we go to the community with bounties, we're blocked.

**Comment by cameron-NEAR** [comment]
So I'm working on creating a Bounties DAO that will allow people to submit their own bounty ideas and be paid to manage them after we find the people to complete them. 

If you have an idea just draft a bounty using the template below and contact me for funding approval (as long as it's below $10k). 

# Description

## Context

# Acceptance Criteria

# Bounty
[$X USD in NEAR]

**Comment by chadlamon** [comment]
this is amazing! I agree on it being a P1

**Comment by crasskitty** [comment]
closing this since @cameron-NEAR has worked on it :)
