### ISSUE TITLE
EPIC - NEAR Bytes Kickoff and First Video

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#11]
Short form, ultra focused video content.

Topics

- [x] sending near with ledger
- [ ] using near-cli (high level)
- [ ] using near-api-js (set up high level)
- [ ] access keys

TODO

Add post and link to gov.near.org

**Comment by thisisjoshford** [comment]
Yes! Certainly need short concise videos on various NEAR functionalities. I've created a `near-cli` high-level one (just needs minor editing and exporting to `.mp4`) and have a simple [node.js project](https://github.com/near-examples/transaction-examples/blob/master/send-tokens-easy.js) that sends NEAR in the easiest way possible (using JS). Would love to create a short 5min "NEAR Byte" to go over this file @mattlockyer. 🙂
