### ISSUE TITLE
[TASK] create one-stop-shop doc for first-touch conversations w/ devs

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#119]
# Proposal for: centralizing first-touch resources that everyone can use in external conversations about NEAR

## What is this? 
-We should have a very clear and concise set of resources about NEAR to share with developers, i.e. welcome! please fill out this form and let us know which opportunities are best for you; want to level up your skills? here's our education program...etc. 

## Who needs to be involved?
-Cameron, Sherif, Matt, Josh, Peter (?)

## Tasks to complete (can return to [x] these)
- [ ] everyone send the one(s) relevant to your vertical to Mally
- [ ] draft the copy you'd suggest saying to the person
- [ ] work with Mally to finalize copy during this sprint (I think this can be all async)

## What priority is this? 
- P2 (Important: known docs, feature requests, or known bugs)

**Comment by crasskitty** [comment]
I'd like to volunteer myself as a resource to set up the automation/trigger flow for this :)

**Comment by nearlyalmonds** [comment]
Great! I'm not 100% sure what that means but would be delighted to have you in the cause. I just want to get everybody on the same page with "what do we tell person X and where are all the links" - like a basecamp of CTAs.

**Comment by cameron-NEAR** [comment]
I absolutely love this initiative and think we should focus on 
1. How the bridge works and why it's important 
2. How NEAR competes against other L1's and L2's 
3. How NEARs account structure works and why this is important for the creator economy 
4. How cross-contract calls work in a sharded blockchain 
5. Why isn't NEAR available to US investors yet

**Comment by doriancrutcher** [comment]
So like a form to best identify a dev's needs and priorities?

**Comment by crasskitty** [comment]
Needs to be reignited?
