### ISSUE TITLE
[TASK] Add TypeDoc documentation to near-api-js

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#124]
# Proposal for: [less than 10 words describing the work to be done]

Cleanup and improve the documentation for `near-api-js` here: https://near.github.io/near-api-js/

## What is this? 
- Organizes the documentation to make it accessible to new developers
- Update docs for correctness

## Who needs to be involved?
- @mehtaphysical 

## Tasks to complete (can return to [x] these)
- [x] update typedoc to the latest version 
- [x] style the typedoc page
- [x] update docs for correctness

## What t-shirt size is this? (range: multi-spint to 1 hour)
medium

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
