### ISSUE TITLE
[TASK] Cross contract calls and promises docs

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#125]
# Proposal for

Create cross contract call documentation for both rust and AssemblyScript

## What is this? 
- Think about best practices for XCC 

## Who needs to be involved?
- @mehtaphysical 

## Tasks to complete (can return to [x] these)
- [x] Intro XCC with use cases and overview of internals
- [X] find best practices for XCC
- [x] XCC with `near-sdk-as`
- [x] XCC with `near-sdk-rs` 
- [x] XCC `near-sdk-as` and `near-sdk-rs` compared
- [ ] XCC simulation testing

## What t-shirt size is this? (range: multi-spint to 1 hour)
large

## What priority is this? (remove what doesn't apply)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by thisisjoshford** [comment]
looove this! @amgando created a repo for this that might be useful :) 
https://github.com/near-examples/cross-contract-calls
