### ISSUE TITLE
[TASK] Get Loomly Rocking & Rolling

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#129]
# Proposal for: Starting up our social media distributer machine "Loomly"

## What is this? 
- A central location where you can upload a piece of content to "Photo, Video, post" & distribute it across all of our social media accounts

## Who needs to be involved?
- @chadlamon 

## Tasks to complete 
- [ ] Link all of NEARs social accounts "Twitter, Youtube, Facebook, Linkedin 
- [ ] Learn how to use all the features it has to offer
- [ ] Clear a budget of $50 a month to fund it
- [ ] Upload the newest Blockheads episode to it for the first test run

## What t-shirt size is this? 
(Small) Full Day

## What priority is this? 
- P2 (Important: known docs, feature requests, or known bugs)
