### ISSUE TITLE
[TASK] Robert - Partners

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#130]
# Proposal for: Help integrate NEAR with partner projects

## What is this? 
- Work with partners and integrate NEAR into their projects

## Who needs to be involved?
- 

## Tasks to complete (can return to [x] these)
- [ ] Partner F: development and testing, support apps dev
- [ ] Partner O: development and testnet launch
- [ ] Partner B & V: design and plan
- [ ] Partner T: run contracts in EVM
- [ ] NEAR Cookbook: for partner developers
- [ ] NFT Demo in Chinese

## What t-shirt size is this? (range: multi-sprint to 1 hour)
medium (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
