### ISSUE TITLE
[TASK] Robert - Meta

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#132]
# Proposal for: miscellaneous tasks for supporting teammates and community

## What is this? 
- Help proof read docs that are translated into Chinese by Homer

## Who needs to be involved?
- Homer

## Tasks to complete (can return to [x] these)
- [ ] Team: Recruit DevRel full-stack dev
- [ ] Event: Rainbow Bridge tech sharing to one developer community
- [ ] Support: Technical posts proof reading: depends on the plan of Homer
- [ ] Support: Validator / Wallet issues follow up

## What t-shirt size is this? (range: multi-spint to 1 hour)
small (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
