### ISSUE TITLE
[EPIC] frontend example for nft-market

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#143]
# Proposal for: title

## What is this? 
- nft-market only has tests, need rough frontend example devs can clone

## Who needs to be involved?
- me

## Tasks to complete (can return to [x] these)
- [x] basic nft minting 
- [x] nft up for sale in NEAR
- [x] offer and accept offer nft with NEAR
- [ ] stretch: fungible token buy/sell e.g. wrapped NEAR and use in market

## What t-shirt size is this? (range: multi-spint to 1 hour)
x-large

## What priority is this? (remove what doesn't apply)
- P0 - partner wants to launch nft-auction Apr 22 that will run for 4 days and accept NEAR + bridge tokens
