### ISSUE TITLE
[TASK] content moderation standards for pluminite

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#147]
# Proposal for: determine how to moderate content on pluminite & submitting a proposal for a grant from the NF

## What is this? 
-  @Patrick1904 raised a good point that with Pluminite we may want to consider some sort of content moderation system. + we need to submit a proposal for a porposal for a grant form NF

## Who needs to be involved?
- @crasskitty maybe @nearlyalmonds for content writing.

## Tasks to complete (can return to [x] these)
- [x] research how other platforms handle this for NFTS
- [ ] come up with a moderation system
- [x] come up with community guidelines
- [x] figure out pricing of the proposal for the NF

## What t-shirt size is this? (range: multi-spint to 1 hour)
 large

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
