### ISSUE TITLE
[TASK] Partner collateral 

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#149]
# Proposal for: centralizing, creating, designing basic collateral for partner conversations

## What is this? 
- 

## Who needs to be involved?
-Mally, Matt, Dani, Peter 

## Tasks to complete (can return to [x] these)
- [ ] standard questions for self-service teams (engineering capabilities and needs)
- [ ] standard questions partners generally ask us
- [ ] generalize recent partner pitch to be reusable
- [ ] create 2 more examples for basic "menu" of what's possible on NEAR
- [ ] revamp NEAR in a Nutshell one-sheet for devs

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
