### ISSUE TITLE
[EPIC] Audit of Awesomenear.com

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#152]
# Proposal for: we need to audit awesomenear.com and figure out what to add to it

## What is this? 
-  We need to audit awesomenear and determine the type of content and what should be on it.

## Who needs to be involved?
- @waverlymaven @cameron-NEAR @crasskitty @elainejykim

## Tasks to complete (can return to [x] these)
- [ ] We need to determine a process to audit awesomenear.com
- [ ] then we need audit it. 
- [ ] Then we need to determine a process for categorizing  all the partnerships/projects
- [ ] then we need to update it

## What t-shirt size is this? (range: multi-sprint to 1 hour)
x-large

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)

**Comment by zavodil** [comment]
I would like to join too since I tried to fork it myself before :)

**Comment by crasskitty** [comment]
hey @waverlymaven who is taking point here or should be? looks like this may have been missed for the current sprint?

**Comment by crasskitty** [comment]
this is in progress, but will span multiple sprints.
