### ISSUE TITLE
[EPIC] OWS website

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#153]
# Proposal for: we're going to stand up a website for OWS

## What is this? 
-  Need to know basis ;)

## Who needs to be involved?
- @potatodepaulo @waverlymaven @crasskitty @nearlyalmonds 

## Tasks to complete (can return to [x] these)
- [ ] figure out the design of the website
- [ ] figure out the content of the website
- [ ] Figure out the SEO
- [ ] Figure out the google analytics 

## What t-shirt size is this?
x-large

## What priority is this? (remove what doesn't apply)

- P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by crasskitty** [comment]
pushed to next sprint :)
