### ISSUE TITLE
[TASK] Adboard for ref.finance

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#154]
# Proposal for: Add pixel party adboard to ref.finance

## Tasks to complete (can return to [x] these)
- [x] update ui to include adboard 
- [x] update services to include adboard
- [x] update pixel party contract to work with ref.finance

## What t-shirt size is this? (range: multi-spint to 1 hour)
(medium)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
