### ISSUE TITLE
[EPIC] eSport partner integration

### ISSUE THREAD

**Issue by zavodil** [near/devrel#155]
# Proposal for: Project integration
Details https://www.notion.so/nearprotocol/Minted-gg-integration-6fefc29caf4849edade10116cbb714a5

## What is this? 
Esport analog of NBA TopShot, project already made an MVP and has strong esport connections

## Who needs to be involved?
- @waverlymaven 

## Tasks to complete (can return to [x] these)
- [x] Show opportunities with NEAR
- [x] Help with code examples
- [ ] Wait for partner approval
- [ ] Find the best approach to launсh in NEAR
- [ ] Prepare cash-to-nft scenario

## What t-shirt size is this? (range: multi-spint to 1 hour)
large

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
