### ISSUE TITLE
[DEVREL RESOURCE REQUEST] Teaching for Sherif!

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#162]
# Proposal for: teaching for sherif's program this week [4/19/2021]

## What is this? 
- Sherif has a program in which he needs people to teach in!

## Who needs to be involved?
- @crasskitty @mehtaphysical & @doriancrutcher are teaching this week with @amgando 

## Tasks to complete (can return to [x] these)
- [x] ash present tuesday
- [x] ryan present wednesday
- [x] dorian present thursday

## What t-shirt size is this? (range: multi-sprint to 1 hour)
, small

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
Ill be presenting with dorian as well, should I assign myself to this?
