### ISSUE TITLE
[TASK] Creating Promo Vid For Sputnik DAO For James For Community

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#170]
# Proposal for: Creating Marketable Video Asset

## What is this? 
- A video asset to shop around to get people hyped before the hackathon

## Who needs to be involved?
- @james

## Tasks to complete 
- [x] Screen record sputnik dao
- [x] Create dynamic titles
- [x] Voiceover
- [x] Create Fresh Intro & outro representing NEAR 

## What t-shirt size is this? 
(medium)

## What priority is this? 
- P2 (Important: known docs, feature requests, or known bugs)
