### ISSUE TITLE
[TASK] Ah-ha moments on NEAR 

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#171]
# Proposal for: aha moments on NEAR 

## What is this? 
- centralize 5-10 common aha moments for NEAR devs

## Who needs to be involved?
- Mally
- Sherif
- Matt
- Vadim
- Peter

## Tasks to complete (can return to [x] these)
- [ ] Mally speak to each person
- [ ] centralize answers for content
- [ ] validate with developer research

## What t-shirt size is this?
small

## What priority is this? (remove what doesn't apply)
P2

**Comment by crasskitty** [comment]
@nearlyalmonds is there any help I can provide here?
