### ISSUE TITLE
[DEVREL RESOURCE REQUEST] hackathon 

### ISSUE THREAD

**Issue by chloethedev** [near/devrel#175]
# Proposal for: [less than 10 words describing the work to be done]
Support from DevRel to co-host Hackathon task sessions
## What is this? 
- For the hackathon task rewards there are 4 planned events to support hackers with their submissions:
1. Ideation Workshop: https://createbase.community/event/ideation-workshop/
2. Presentation Workshop: https://createbase.community/event/presentation-workshop/
3. VIdeo Workshop:https://createbase.community/event/video-demo-workshop/
4. Github Submission Workshop: https://createbase.community/event/full-github-submission-workshop/

## Who needs to be involved?
- 

## When do you need this work completed by?
- First session is May 16th (Ideation) and the others are each following Friday of the event for a total of 4 sessions. 

## Tasks to complete (can return to [x] these)
- [x] Support for Ideation: https://createbase.community/event/ideation-workshop/
- [ ] Support for Presentation: https://createbase.community/event/presentation-workshop/
- [ ] Support for Video Demo: https://createbase.community/event/video-demo-workshop/
- [ ] Support for Github Submission: https://createbase.community/event/full-github-submission-workshop/

## What t-shirt size is this? (range: multi-sprint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P0 (EMERGENCY: drop everything to put out the fire)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
- P2 (Important: known docs, feature requests, or known bugs)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by crasskitty** [comment]
Hey @chloethedev , what type of resources are you asking for here (i.e. developer support, content, ect) , or do you know exactly who form DevRel you will need help fro?

**Comment by chloethedev** [comment]
I sent Dani an email about this and she said she would bring up the specifics in the next sprint meeting. 

Goal is to have 4 live events over the course of the hackathon to help participants with their submissions. Content will be streamed and recorded for future use. I don't know who exactly would be best for each task/event. The goal would be to have people sign up that are interested in the topic and would like to support the community. 

(Ticked off the first task because Jaye confirmed her attendance and will be leading that session)

**Comment by crasskitty** [comment]
@crasskitty @thisisjoshford @waverlymaven are in charge of this

@crasskitty -- to help coordinate the office hours
@thisisjoshford - to coordinate the discord support schedule
@waverlymaven  - to facilitate the filling of the office hours/ comms between community & devrel
