### ISSUE TITLE
[DEVREL RESOURCE REQUEST] 

### ISSUE THREAD

**Issue by Kisgus** [near/devrel#184]
# Proposal for assistance with Sputnik DAO v2 contract documentation

## What is this? 

Core contracts for Sputnik DAO v2 framework

## Who needs to be involved?

A talented technical writer, we have a dev that can help with questions who looked deep into this for 1-2 weeks already

## When do you need this work completed by

The Gitcoin Open Web NEAR hackathon starts in 1 week and 1 day from now. It would awesome to have well documented contracts by then so all the hackers can use these to hack on for the hackathon and help iterate the contract and the documentation

## Tasks to complete (can return to [x] these)
- [ ] Onboarding call chat with dev who into the contract and started documentation 
- [ ] Review of current documentation (by a native english technical writer)
- [ ] Test it out on hackathon and help resolve queries

## What t-shirt size is this? (range: multi-sprint to 1 hour)

Small

## What priority is this? (remove what doesn't apply)

I consider this P1 for getting most out of the Gitcoin hackathon

**Comment by amgando** [comment]
Gitbook is fine for docs. 

I would recommend that we  start with some structure, like an outline, then split up the work of each part. 

Someone should play editor to review all the content and make it sound like one voice.

Here's a quick draft of an outline. We should definitely have some organizing structure to start with and this is just one idea. Maybe others can also suggest ideas that we can discuss in the kickoff meeting and agree on one outline to start working on


ORIENTATION 

(can be 90% links to other content already online like YouTube, etc with 500 new words) 

- what is a DAO? 
- why do we need DAOs? 
- how do we use DAOs? 
- who is using DAOs? 

SPUTNIKDAO v1 

(can be very simply intro, maybe 500-1000 new words max) 

- what could it do? 
- what did people do with it? 
- what was missing?

SPUTNIKDAO v2

- what is new / different?
- envisioning possible use cases

DAO TOKEN

- why token?
- how to configure token?
- how to use token?

DAO GROUPS

- why groups?
- how to configure groups?
- how to use groups?

DAO POLICIES

- why policies?
- how to configure policies?
- how to use policies?
- policies and groups
- advanced policy scenarios 

DAO BOUNTIES

- why bounties?
- how to configure bounties?
- how to use bounties?
- bounties and policies
- advanced bounty scenarios

DAO UPGRADES

- why upgrades?
- how / when to use upgrades?

DAO COMMAND REFERENCE

- list of all possible commands
- popular scenarios and command recipes

DAO SOURCE CODE

- inspecting the source code
- building the source code
- verifying deployment integrity using code hash
- understanding deterministic builds

DAO IN THE WILD

- who's using SputnikDAO v2?

**Comment by amgando** [comment]
https://meet.google.com/sgw-gxii-jib

Kickoff meeting scheduled for Monday, May 10 @ 6-7pm GMT+3

**Comment by thisisjoshford** [comment]
Documentation progress is currently blocked as we wait for Sputnik DAO [PR #11](https://github.com/near-daos/sputnik-dao-contract/pull/11) merger that will alter contract functionality. According to DenysK, this will take place sometime tomorrow (5/13/21).

**Comment by thisisjoshford** [comment]
**UPDATE:**
DenysK will be updating the README with basic create/deploy/call commands for Sputnik DAO v2 after PR has been reviewed and merged (hopefully tomorrow 5/13/21). He will then review the contracts and their functionality advising @amgando and myself of what he would like us to have documented by next Friday (5/21/21).

**Comment by thisisjoshford** [comment]
**UPDATE:**
[PR #11](https://github.com/near-daos/sputnik-dao-contract/pull/11) has been merged and DenysK is now testing functionality and creating a list `near-cli` commands that @amgando and I will document. Waiting for his green light to start this process.
