### ISSUE TITLE
[EPIC] productize the next near example app!

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#186]
# Proposal for: productizing a new near example app using the process and flows and learnings from pluminite.com

## What is this? 
- Applying the learnigns from my first productizing example app, I will pick the next example app from @mattlockyer 's repo and work with @waverlymaven and possible @potatodepaulo to decide the next one to work on. 

End goal: launch it on product hunt

## Who needs to be involved?
- @crasskitty @mattlockyer @waverlymaven @potatodepaulo @nearlyalmonds @chadlamon  ...the rest TBD
- contract designer or a new fulltime designer tbd

## Tasks to complete (can return to [x] these)
- [ ] use the flow from pluminite.com launch to make a new product using @mattlockyer's example apps
- [ ] decide on which example app to productize
- [ ] make a product idea
- [ ] wireframes
- [ ] design
- [ ] eventually, any engineering needed
- [ ] marketing materials for producthunt
- [ ] ...more tbd

## What t-shirt size is this?
x-large

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
