### ISSUE TITLE
[EPIC] Full workshop for live demos

### ISSUE THREAD

**Issue by behaviary** [near/devrel#190]
## What is this for? 
- This is the first of a series of workshops for our events strategy moving forward. A complete workshop should serve as a fun introduction to coding up NEAR apps to a strong beginner, or intermediate engineer. 

## Who needs to be involved?
- @mehtaphysical @doriancrutcher @thisisjoshford @nearlyalmonds 

## Tasks to complete (can return to [x] these)
- [ ] A specific subset of features that we want to demonstrate 
- [ ] A clean example app from start to finish
- [ ] A presentation that is a step by step guide for building the app
- [ ] A place to capture dev leads at the end of the workshop

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [x] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [x] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
