### ISSUE TITLE
[EPIC or TASK] testing again disregard

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#193]
## What is this for? 
- 

## Who needs to be involved?
-

## Tasks to complete (can return to [x] these)
- [ ] todo 1... 
- [ ] 2...

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ ] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
