### ISSUE TITLE
[REQ] The Beta Community Program

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#195]
## What is this for? 
- Setting up the beta wallet community program

## Who needs to be involved?
 - @crasskitty @stefanopepe @icerove @TiffanyGYJ 

## Tasks to complete (can return to [x] these)
@stefanopepe 

- [ ] Make mailchimp templates and emails - by May 20th
- [ ] Determine which environment this will be on (staging, testnet, ect,) and tell @TiffanyGYJ and @icerove  - by May 21st
- [ ] determine flags for mixpanel (0 tranasactions, 50, 500, etc) - by May 21st
- [ ] make a list of questions for @crasskitty for the airtable form
- [ ] distribute airtable form
- [ ] determine how to get people to claim their rewards

@crasskitty 

- [ ] make airtable form
- [ ] integrate the form responses into a whitelist on mixpanel
- [ ] integrate mixpanel flags back into airtable
- [ ] set up mailchimp integration for airtable

@TiffanyGYJ @icerove 

- [ ] set up mixpanel tracking for the desired environment
- [ ] set up mixpanel flags
- [ ] help @crasskitty with two way airtabel x mixpanel sync

## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
 x-large

## What priority is this? (remove what doesn't apply)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by crasskitty** [comment]
@TiffanyGYJ @stefanopepe @icerove I accidentally closed the tab with the issue, so I resubmitted from memory, can you double check the list and edit anything missing?

**Comment by stefanopepe** [comment]
Looks good to me! Will add some dates to my tasks, so we can check if I'm on track =)
