### ISSUE TITLE
[REQ] Investigate Further Testing Workflow Improvements

### ISSUE THREAD

**Issue by DiscRiskandBisque** [near/devrel#217]
## What is this for? 
- Testing workflow improvements, specifically:
  - Adding a `near test` command to `near-cli`
  - Deprecating `near-sdk-sim` in favor of a local development specific near node (as yet unnamed, internally called `near-Ganache`)
  - [Design Doc](https://docs.google.com/document/d/10xKfwVhJIAYNVkgR0FPvzpsnI8-Gs9GgblygGGT1sxs/edit?usp=sharing)
- Additional Color: I'm confident in the initial implementation since we're bringing our experience up to par with competitors, but I would like to know more from users on where it could go, in addition to what testing needs are unique to NEAR. I marked this is important rather than critical since there's not future work blocked at this moment, but it will be needed research going forward.

## Who needs to be involved?
- @mattlockyer and/or @mehtaphysical 
- @DiscRiskandBisque

## Tasks to complete (can return to [x] these)
- [ ] Gather more information on existing pain points around
  - [ ] testing NEAR contracts
  - [ ] NEAR's local development experience

## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [x] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [x] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
