### ISSUE TITLE
[TASK] Create An Anchor Podcast Channel For NEAR

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#221]
## What is this for? 
- To grow NEAR's awareness & expand its audience by publishing an amazing first podcast episode 

## Who needs to be involved?
- no one else yet.

## Tasks to complete (can return to [x] these)
- [ ] Create An Anchor Account
- [ ] Convert video into audio, design a thumbnail, type a description, link near.org & all social handles
- [ ] Schedule to be posted on friday @3pm

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] small

## What priority is this? (remove what doesn't apply)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
