### ISSUE TITLE
[TASK] Create 5-8 pieces of micro content from the Berkeley city council meeting

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#222]
## What is this for? 
- For gaining awareness on Instagram, Twitter, Linkedin and facebook by uploading bite sized 2-4 minute highlights of the interview with Ben Bartlett

## Tasks to complete (can return to [x] these)
- [ ] create 3 pieces of micro content 
- [ ] create 3 pieces of micro content 
- [ ] create 2 pieces of micro content 
- [ ] Upload & Automate scheduled posts in _Sprout social_
- [ ] Create a marketing campaign 

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ x] medium

## What priority is this? (remove what doesn't apply)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
