### ISSUE TITLE
[REQ] Add support for secp256k1 keys in near-api-js

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#223]
## What is this for? 
- Add secp256k1 support to `near-api-js` to help with EVM devX

## Who needs to be involved?
- @mehtaphysical 

## Tasks to complete (can return to [x] these)
- [ ] Update `borsh-js` to allow better  serialization/deserialization of public keys https://github.com/near/borsh-js/issues/19
- [ ] Replace tweetnacl with elliptic library in near-api-js
- [ ] Add secp256k1 support to near-api-js https://github.com/near/near-api-js/issues/440

## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ ] medium
- [X] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [X] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
