### ISSUE TITLE
[TASK] Bounties Code Review

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#230]
## What is this for? 
- Code review for bounties

## Who needs to be involved?
- @mehtaphysical 

## Tasks to complete (can return to [x] these)
- [ ] https://github.com/near/bounties/issues/49
- [ ] https://github.com/near/bounties/issues/50
- [ ] https://github.com/near/bounties/issues/48

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [X] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [X] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
