### ISSUE TITLE
[EPIC] Blockchain Summer Website

### ISSUE THREAD

**Issue by elainejykim** [near/devrel#232]
## What is this for? 
- Compilation of Blockchain events hosted in different cities/countries.
- https://miami-blockchain-wekk.web.app/

## Who needs to be involved?
- Me! @waverlymaven 

## Tasks to complete (can return to [x] these)
- [x] Initial static website
- [x] Branding/design
- [x] Connect firebase database
- [x] Get a domain

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ ] medium
- [X] large
- [x] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [x] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
