### ISSUE TITLE
[EPIC] retroneon

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#233]
## What is this for? 
- Retroneon.art <--- a place for our dope as NFT experience 

## Who needs to be involved?
- @doriancrutcher @elainejykim @crasskitty @cameron-NEAR @waverlymaven 

## Tasks to complete (can return to [x] these)
- [ ] design the website
- [ ] connect the api things
- [ ] get partnerships (cc: @cameron-NEAR )
- [ ] build the dapp

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
emergency because we have a deadline in 2 weeks D:

**Comment by chadlamon** [comment]
I loved seeing it this morning! Please let me know if you need a promo vid for it

**Comment by cameron-NEAR** [comment]
I love the tangible use-case for NFTs!! What kind of partnerships are you
looking to establish?

I'm happy to hop on a 1-2 hour call Friday or early next week to fill
out a business
model canvas <https://en.wikipedia.org/wiki/Business_Model_Canvas>. I've
participated in and run a few startup weekends and I'm confident we can
create an actionable roadmap pretty quickly. Let's get it done 💪🏽
