### ISSUE TITLE
[REQ] near-api-js uses typescript files for tests

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#234]
## What is this for? 
- Improve the way tests are run in `near-api-js`

## Who needs to be involved?
- @mehtaphysical 

## Tasks to complete (can return to [x] these)
- [ ] Use TypeScript files to run tests

## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [X] small
- [ ] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [X] P3 (Nice-to-have: docs or features that improve a flow)
