### ISSUE TITLE
[REQ] near-cli tests leave artifacts

### ISSUE THREAD

**Issue by mehtaphysical** [near/devrel#235]
## What is this for? 
- `near-cli` tests leave artifacts https://github.com/near/near-cli/issues/761

## Who needs to be involved?
- @mehtaphysical 

## Tasks to complete (can return to [x] these)
- [X] add to the `.gitignore` to remove artifacts

## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
- [X] x-small
- [ ] small
- [ ] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [X] P3 (Nice-to-have: docs or features that improve a flow)
