### ISSUE TITLE
(EPIC) Collab.Land Interview  

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#239]
## What is this for? 
- Macro content, Micro content, Gifs & an anchor podcast

## Who needs to be involved?
- The whole team, ill need feedback! Im curious who even reads these? Heart this proposal if you've read it 

## Tasks to complete (can return to [x] these)
- [x] Rough draft 1 
- [x] Rough Draft 2
- [ ] Final Draft
- [x] 3-5 Pieces of micro content 
- [ ] Upload to NEARs Anchor Podcast channel
- [ ] Create Thumbnail 
- [ ] Upload to all Socials & back it with a $50 ad budget 

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] Shmedium

## What priority is this? (remove what doesn't apply)
- [ ] P2 (Important: known docs, feature requests, or known bugs)

**Comment by thisisjoshford** [comment]
Hey @chadlamon, just checking in on the status of this issue.
