### ISSUE TITLE
[EPIC] BlockHeads Near-Api-JS In a Nutshell 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#240]
## What is this for? 
Let's make a clean succinct video detailing the essentials of near-api-js

## Who needs to be involved?
- @chadlamon 
- @thisisjoshford (for Q's and support)
- @mehtaphysical (for Q's and support)
- @thisisjoshford  (for Q's and support) 
## Tasks to complete (can return to [x] these)
- [ ] Create slide deck for video going over what we will cover and create visuals for concept 
- [ ] Create example application for steps progression ( reuse of classic voting app?) 
- [ ] Record Video 
- [ ] Review Content 
- [ ] Chad stitches video togther 

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)

- [ ] medium

## What priority is this? (remove what doesn't apply)

- [ ] P2 (Important: known docs, feature requests, or known bugs)

**Comment by mehtaphysical** [comment]
This sounds awesome! My land perfect with the `near-api-js` v1 release.

**Comment by chadlamon** [comment]
Let me know about this asap!

**Comment by thisisjoshford** [comment]
I still think this is a great idea and we should work on this @doriancrutcher @chadlamon :) Let's get this on our roadmap.
