### ISSUE TITLE
[EPIC] RTC x NEAR cohort

### ISSUE THREAD

**Issue by elainejykim** [near/devrel#242]
## What is this for? 
- https://rewritingthecode.org/ and NEAR will have partnered education program
- 4~6 week program for technical and nontechnical women in tech.

## Who needs to be involved?
- me
- @waverlymaven 
- + will need help moving forwards

## Tasks to complete (can return to [x] these)
- [ ] nail down program details
- [ ] create program content
- [ ] execute on the program
- [ ] create and manage community space for the cohort members
- [ ] set up needed resources/platforms/etc

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ ] medium
- [ ] large
- [X] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [X] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
