### ISSUE TITLE
[Task] Review and create presentation on microbonds grant

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#244]
Review application and create presentation for grant committee

## What is this for? 
- 

## Who needs to be involved?
- @doriancrutcher 

## Tasks to complete (can return to [x] these)
- [ ] Review Grant Application 
- [ ] Create presentation 
- [ ] Present to grant comittee

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)

- [ ] small

- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
