### ISSUE TITLE
[REQ] BSN Web Portal for NEAR Developers

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#248]
## What is this for? 

Based on our collaboration with BSN, we now own an enterprise account which has a large number of RPC Nodes (counted by # of requests) that we can provides to our developers. To make the requests usable to developers, we can build a web portal to help developers set up free or paid RPC nodes in several minutes (and also archival nodes, which is under discussion with the partner), as an alternative solution to Figment Datahub and other node services. 

More details about the design of the web portal can be found here: https://hackmd.io/@L9ZnGph8Tbaio2GVX_z-EA/B1_1yl45u

## Who needs to be involved?
- Robert
- developers from DevRel if we have anyone who can join
- BSN engineers

## Tasks to complete (can return to [x] these)
- [ ] design of the BSN web portal
- [ ] ask developers who might be interested to join
- [ ] develop the alpha version of web portal for testnet
- [ ] release the web portal to developers

## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ ] medium
- [x] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [x] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
