### ISSUE TITLE
[EPIC] Voting App Tutorial 2.0 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#251]
## What is this for? 
- Creating a new and updated version of the blockheads voting application tutorial since the first version got so much organic traction 

## Who needs to be involved?
- @chadlamon 
- @doriancrutcher 

## Tasks to complete (can return to [x] these)
- [ ] Create the voting applicaiton 
- [ ] Create tutorial slides
- [ ] Record assets for chad
- [ ] edit video
- [ ] post on youtube and social media 

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ x] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [x ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
