### ISSUE TITLE
[TASK] Near Auth documentation & improvements

### ISSUE THREAD

**Issue by zavodil** [near/devrel#252]
## What is this for? 
- Help builders to use Social links of their users

## Who needs to be involved?
- @zavodil 
- @thisisjoshford 

## Tasks to complete (can return to [x] these)
- [ ] Create github documentation
- [ ] Try documentation with developers
- [ ] Create an example
- [ ] Introduce missing social networks

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] medium

## What priority is this? (remove what doesn't apply)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
