### ISSUE TITLE
[TASK] Pluminite improvements

### ISSUE THREAD

**Issue by zavodil** [near/devrel#253]
## What is this for? 
- extra features for pluminite

## Who needs to be involved?
- @zavodil 

## Tasks to complete (can return to [x] these)
- [ ] fix flow if github blacklist is banned
- [ ] introduce auctions
- [ ] update market contract

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] medium

## What priority is this? (remove what doesn't apply)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
