### ISSUE TITLE
EPIC - EPAM onboarding (corgis & ...)

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#26]
- [x] corgis first preview
- [x] corgis tested
- [x] corgis meet reqs
- [x] final demo
- [x] sign off on corgis
