### ISSUE TITLE
[TASK] ~ Login to NEARs Instagram & respond to 30 messages 

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#309]
## What is this for? 
- Social Media Etiquette 
- There were a-lot of messages that were left unattended. Literally I reposted 2 different peoples story posts because they were hyping us up and posting about us. Its free advertisement for our Metabuidl hackathon in two days & mintbase. 

- Ill continue checking our instagram at least once a week. In general I engaged with about 40 different people saying thank you for mentioning us on their stories to keep up a good repertoire & make them feel HEARD.  

## Who needs to be involved?
- Anyone that has NEARs instagram login lol

## Tasks to complete (can return to [x] these)
- [x] Respond to 40 unopened messages 
- [x] Repost stories others have mentioned us in
- [x] Like some of the users posts that messaged us and showed us love
- [x] reposted our metabuidl post to our story for advertisement 

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [x] x-small

## What priority is this? (remove what doesn't apply)
- [x] P2 (Important: known docs, feature requests, or known bugs)
