### ISSUE TITLE
[TASK] Create a Zero to Hero NFT Guide for Docs which includes a Marketplace. 

### ISSUE THREAD

**Issue by BenKurrek** [near/devrel#382]
## What is this for? 
- This will be the staple example of using smart contracts on NEAR in our dev docs. It will start with the simplest example of using an existing NFT contract to mint an NFT and have it show in your wallet. By the end, users will have coded a functional NFT marketplace from scratch with very well commented code.

## Who needs to be involved?
- @BenKurrek 
- @bucanero 
- @doriancrutcher
- @thisisjoshford 

## Tasks to complete (can return to [x] these)
- [x] brainstorm milestones and how to section the tutorial / journey.
- [x] create a template repo that is well structured (better structured than the current repos). 
- [x] create a skeleton branch that builds properly
- [x] create a minting branch that has the bare minimum essentials for being able to display an NFT in the wallet
- [x] create an enumeration branch that goes through the enumeration standard
- [x] create an nft_core branch that goes through the core standard.
- [x] create an approvals branch that goes through the approvals standard
- [x] create a royalty branch that goes through the royalty standard
- [x] create an events branch that goes through and implements the events standard
- [x] introduce the marketplace contract 
- [ ] create a complete guide in docs that goes through all the above in detail.

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [ ] small
- [ ] medium
- [X] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [X] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by BenKurrek** [comment]
GH Repo containing all the branches and commented code: 
https://github.com/near-examples/nft-tutorial

**Comment by BenKurrek** [comment]
Creating an outline for the structure in docs in this google doc: 
https://docs.google.com/document/d/18DQUgiOR8qbOatosupx4tZeyQh6VKcTXOTC6G2Cj684/edit?usp=sharing

**Comment by BenKurrek** [comment]
Upgraded all the contracts to the new SDK 4.0.0-pre4 as well as the new rust toolchain. I also added a new branch for events and refactored the codebase to provide very clear changes that need to be made across branches when comparisons are made.
