### ISSUE TITLE
[TASK] Follow up with folks from the GLITCH residency to partner them with NEAR and Fayyr. 

### ISSUE THREAD

**Issue by BenKurrek** [near/devrel#384]
## What is this for? 
- Some members of the GLITCH residency want to continue using NEAR and they loved Fayyr's mission. I want to create a partnership between Fayyr and both Lady PheOnix and Tony. They will help spread NEAR and Fayyr's message to try and create a standard for charities and have Fayyr be the leading platform for everything charitable across all chains. 

## Who needs to be involved?
- @BenKurrek 

## Tasks to complete (can return to [x] these)
- [X] Meet with Tony
- [X] Meet with Lady PheOnix

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [X] small
- [ ] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [X] P3 (Nice-to-have: docs or features that improve a flow)
