### ISSUE TITLE
[TASK] Run Rust Workshops Babylon Hackathon

### ISSUE THREAD

**Issue by BenKurrek** [near/devrel#385]
## What is this for? 
- I was asked to run 2 Rust workshops for the Babylon Hackathon. I will go through the minting branch of my zero to hero NFT tutorial and explain all the code and have an NFT show up in my wallet at the end. I will also talk about the grants program, what's special about NEAR (account model, access keys etc), and the resources NEAR can provide (office hours, discord, white glove treatment etc.) My slides can be found here: 

https://docs.google.com/presentation/d/1eGqsMNZcUIyJ3MqLW3BeI4FYZ1MMG8AHLTPt6a97yCs/edit?usp=sharing

## Who needs to be involved?
- @BenKurrek 

## Tasks to complete (can return to [x] these)
- [x] create a pitch deck to go through in the workshops
- [x] hold the workshops

## What is the t-shirt size of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] x-small
- [X] small
- [ ] medium
- [ ] large
- [ ] x-large

## What priority is this? (remove what doesn't apply)
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [X] P3 (Nice-to-have: docs or features that improve a flow)
