### ISSUE TITLE
EPIC- EthDenver 2021 Retro

### ISSUE THREAD

**Issue by potatodepaulo** [near/devrel#4]
- [x] Rough retro provided to team
- [x] Full metrics gathering and report? (Tiffany?)
- [x] Official writeup of how it went? 4NTS?
- [x] ...? @potatodepaulo ?
