### ISSUE TITLE
[EPIC] Productization Process for Example Apps

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#43]
# Proposal for: Productizing NEAR Example Apps

## What will be accomplished by completing this and who will it impact?
If we can take the example apps and turn them into memeable, sharable mini products, we can use those mini products to help onboard people to learn how to use those tools.

## Which OKR(s) do this relate to?

- [x] 1. Increase the number of **successful** apps running on MainNet
- [x] 2.  Increase the number of **successful** developers deploying and improving their apps on TestNet
- [x] 3. Support the continued maintenance of the materials that will allow devs to self-serve and be **successful**

## What resources do you need to accomplish this?
- @potatodepaulo 's time, to help me iterate on these mini products.
- A contract designer, already have one in mind
- @mattlockyer 's time, aysnc to answer any questions
- @nearlyalmonds help with copy
- @zavodil's time as a developer :)

## What t-shirt size is this?

- [x] x-large (needs to be broken into smaller tasks, most likely an Epic)
- [ ] large (whole sprint & shouldn't be done alone)
- [ ] medium (anything half a week to a week)
- [ ] small (anything from half a day to a full day)
- [ ] x-small (less than half a day)

## What priority is this?

- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [x] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

## To Do:
- [x] do this for the first time with this repo: https://github.com/near-apps/nft-launcher
- [x] One page lite- PRD  : https://www.notion.so/nearprotocol/PRD-NFT-App-Marketplace-43786251858345b59d76c27fac95ade4
- [x] designer picked out and contracted : Ann Beaver : See our product mockups here: https://www.figma.com/file/4jw0XVE1i4bBLbHBIp6MoT/PLUMINITE?node-id=7%3A89
- [x] Work with @nearlyalmonds on copy for the post/ story/ intro to the product for product hunt
- [x] Find a dev to build out the front end! (possibly post to sputnik.fund as a bounty? Work with @jlwaugh and @cameron-NEAR to find someone!)
- [x] work with designer one- page screenshot of the app, naming, & logo for the app

## Desired Outcome:
- We can post this on Product hunt. 
- Should have a 
- [ ] story
- [ ] screenshot that's clean and design filled
- [ ] logo
- [ ] Description that's a story
- [ ] a call to action for people to try it
- [ ] a call to action to engage with us/ give us feedback

Example: https://www.producthunt.com/posts/vantage-2

**Comment by crasskitty** [comment]
Added major updates to the actual file, but at this point, the PRD is roughly done: https://www.notion.so/nearprotocol/PRD-NFT-App-Marketplace-43786251858345b59d76c27fac95ade4

And the figma file with the prototype of the app is coming along: https://www.figma.com/file/4jw0XVE1i4bBLbHBIp6MoT/PLUMINITE?node-id=7%3A89

Pretty much my only blocker at this point is finding a dev to implement, which I need @cameron-NEAR and @jlwaugh to help with :)

**Comment by crasskitty** [comment]
Looks like @zavodil has volunteered some of his time to help, and I have a lead with another dev thanks to @cameron-NEAR 👍

**Comment by zavodil** [comment]
Totally agree! I guess it is the most wanted example app now.
I'm sure we have to keep it simple, and release only with the basic (and most wanted) functionality
we have contracts for nft and nft-market now https://github.com/near-apps/nft-market/tree/main/contracts

**Comment by crasskitty** [comment]
Need to get a grant proposal to @waverlymaven by mid week
