### ISSUE TITLE
[EPIC] Revamp NEAR's VC Referral Network

### ISSUE THREAD

**Issue by cjd425** [near/devrel#46]
# Proposal for: Implement a seamless process to source investment opportunities of projects fundraising in the NEAR ecosystem. 

## What will be accomplished by completing this and who will it impact?
- Connect projects that are building on NEAR and raising money to our VC's so they recommend NEAR to other projects in their portfolios. 

## Which OKR(s) do this relate to?
- [x] 1. Increase the number of **successful** apps running on MainNet
- [x] 2.  Increase the number of **successful** developers deploying and improving their apps on TestNet
- [ ] 3. Support the continued maintenance of the materials that will allow devs to self-serve and be **successful**

## What resources do you need to accomplish this?
- Help from Dani + Mimi and cooperation from the executive team. 

## What t-shirt size is this?

- [ ] x-large (needs to be broken into smaller tasks, most likely an Epic)
- [X] large (whole sprint & shouldn't be done alone)
- [ ] medium (anything half a week to a week)
- [ ] small (anything from half a day to a full day)
- [ ] x-small (less than half a day)

## What priority is this?

- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [X] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

Learn more about this initiative here: https://www.notion.so/nearprotocol/VC-Referral-Network-4a5ba7497358411d99c8ec73d25325a7 

#### Also, feel free to comment with your questions, concerns, thoughts, to volunteer yourself as a resource, or to tag in other people who may have more context!

**Comment by crasskitty** [comment]
@cjd425 agree, this is a LARGE, p2 Epic!
