### ISSUE TITLE
[EPIC] Revamp Bounties Program

### ISSUE THREAD

**Issue by cjd425** [near/devrel#47]
# Proposal for: Increasing the amount of submitted and completed bounties.

## What will be accomplished by completing this and who will it impact?
- Implement a process to reward technical and non-technical contributors who accelerate education, development, and adoption of the NEAR Protocol.

## Which OKR(s) do this relate to?

- [x] 1. Increase the number of **successful** apps running on MainNet
- [X] 2.  Increase the number of **successful** developers deploying and improving their apps on TestNet
- [X] 3. Support the continued maintenance of the materials that will allow devs to self-serve and be **successful** 

## What resources do you need to accomplish this?
- Time and feedback from previous Bounty Managers and Submitters: Vadim, Kendal, Mike, Chad, and Illia. 

## What t-shirt size is this?
- [X] x-large (needs to be broken into smaller tasks, most likely an Epic)
- [ ] large (whole sprint & shouldn't be done alone)
- [ ] medium (anything half a week to a week)
- [ ] small (anything from half a day to a full day)
- [ ] x-small (less than half a day)

## What priority is this?
- (delete this line) select one by putting a `x` inside the relevant brackets. If it is a true P0, we cannot finish this sprint without accomplishing it. Use sparingly.

- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [X] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

Learn more about this program here: https://www.notion.so/nearprotocol/Revamped-Bounties-Program-7220b11845d045bdb41d41fa1452361c

**Comment by crasskitty** [comment]
Hey @cjd425 , great idea/proposal.

My question for you-- why is this a P1-- what about it makes it critical? I'm unsure about the P1, but agree is an X-LARGE t-shirt size, as it is an epic and will take a ton of steps.

From what I can see, we have bounties right now and afaik, they are being shipped out to contributors? Is that not the case? Can you provide some context on what the CURRENT scenario is for this program?

Also, I can't view the notion doc!

**Comment by potatodepaulo** [comment]
This is super important! We should get this done within the next sprint. I worked on the previous bounty program, it was WAY harder than I thought it was. We need to break this into a ton of small issues, but it's cool that this is an epic. Hard to scope.

P1, T-shirt: XL

**Comment by cjd425** [comment]
@crasskitty - I'd consider this critical because we lack clear and consistent call to actions to engage our technical community members. A robust bounties program will serve as a key component to attract new talent and then push towards more long-term projects. The sooner we get this done, the better.

**Comment by crasskitty** [comment]
@cjd425 I guess I'm still lacking context -- do we NOT have a functional bounty program rn? (if so, I am unaware)

I agree this will be a big task to take on, but what I'm trying to evaluate is priority. i.e. if we dont have anything working in place rn, that makes this a P1 in my mind. If we do, its a p2, maybe a P3?

**Comment by cjd425** [comment]
@crasskitty - We do have something in place but there are many times where questions go unanswered and devs in the community feel unappreciated.

**Comment by crasskitty** [comment]
Ok, thanks for the context @cjd425 

P2 |  T-shirt: XL

**Comment by nearlyalmonds** [comment]
I volunteer to help with the writing/framing of this @cjd425
