### ISSUE TITLE
[Epic] Music App episode 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#48]
# Proposal for: BlockBop Music App/Competiton Video

## What will be accomplished by completing this and who will it impact?
This will increase awareness of what developing on the NEAR protocol could produce in terms of creative DApps and bring a more "human element" to our channel. This will also bring in more viewers and subscribers to NEAR's youtube channel

## Which OKR(s) do this relate to?

- [ ] 1. Increase the number of **successful** apps running on MainNet
- [x] 2.  Increase the number of **successful** developers deploying and improving their apps on TestNet
- [x] 3. Support the continued maintenance of the materials that will allow devs to self-serve and be **successful**

## What resources do you need to accomplish this?
-Editor (Chad Lamon) 
- Music Artists (Chad Lamon) 
- Event Assistance (@nearlyalmonds )

## What t-shirt size is this?

- [ ] x-large (needs to be broken into smaller tasks, most likely an Epic)
- [x] large (whole sprint & shouldn't be done alone)
- [ ] medium (anything half a week to a week)
- [ ] small (anything from half a day to a full day)
- [ ] x-small (less than half a day)

## What priority is this?

- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [ ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [x] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by crasskitty** [comment]
Hi @doriancrutcher ! 

A few questions before I can weigh in with my votes.


Are there multiple tasks that will go into shipping this that will require more than an x small amount of work?
 i.e. are there individuals parts of this Epic or tasks that will take more than 1/2 of a day to accomplish this? 
 
 Can you describe more about what you're doing here? I.e. I see that @nearlyalmonds would be involved in an event-- how does an event tie into this?
 
 Thanks!

**Comment by chadlamon** [comment]
Im curious to find out more on how the app works! Would people be able to download the artists music from this app?

**Comment by nearlyalmonds** [comment]
Are there 2 tasks related to the same thing? I think I saw one from @chadlamon as well. In any case, I'm no event expert but I'm totally down to help as much as I can and bring in other expertise :)

**Comment by crasskitty** [comment]
@crasskitty I'll volunteer my time to help with the event
