### ISSUE TITLE
🔷 [Epic] `Docs` enhancements for Chain Abstraction

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#494]
### Background

Proximity is preparing for a hackathon end of January 2025 and has reviewed our chain abstraction docs & examples, providing the following feedback:
https://docs.google.com/document/d/1IiQA4SadV4GAsHvz-Q-beGV849DzaPyXxAQoTWAjG0w/edit?tab=t.0

### Scope

Act on the feedback above by converting them into action items /tasks and shipping these changes by mid January 2025. (Hackathon Begins ~~1/27/25 / Registration is 1/22/25~~ UPDATED -> 2/11/2025) 

### Related Initiative

- https://github.com/NEAR-DevHub/.github/issues/17

### Related Tasks

```[tasklist]
- [ ] https://github.com/near/docs/issues/2379
- [ ] https://github.com/near/docs/issues/2380
- [ ] https://github.com/near/docs/issues/2381
- [ ] https://github.com/near/docs/issues/2430
- [ ] https://github.com/near/docs/issues/2287
- [ ] https://github.com/near/docs/issues/2431
```

### Priority

🟠 P1 : High
