### ISSUE TITLE
[EPIC] NEAR LABS

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#63]
# Proposal for: Set up workflows for NEAR Labs

## What is this? 
- TBD

## Who needs to be involved?
-Peter and Dani

## Tasks to complete
[ ] - RC info from dev shops
- Paperwork with legals/opps
- POC

## What t-shirt size is this?
- [ ] x-large 
- [ ] large 
- [ X] medium
- [ ] small 
- [ ] x-small 

## What priority is this?
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [X ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
