### ISSUE TITLE
[EPIC] Grants Optimizations

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#64]
# Proposal for: Implementing the grant process updates/optimizations

## What is this? Optimizing process to address the bottlenecks and address feedback 
- 

## Who needs to be involved?
-Dani & Gus

## Tasks to complete
- Set up new Subject Matter Expert program for engineers
- Set up Subject Matter Experts in "other" categories
- Handover between legals/opps/grants
- Set up Demo Day structure and lineup
- Actively manage grants set
- Hiring process for GC and GM

## What t-shirt size is this?
- [ ] x-large 
- [X ] large 
- [ ] medium
- [ ] small 
- [ ] x-small 

## What priority is this?
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [x] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)
