### ISSUE TITLE
[TASK] NFTs

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#65]
# Proposal for: NFT Project

## What is this? TBD
- 

## Who needs to be involved?
-Dani, Matt, and Mally

## Tasks to complete
-Review architecture
-Scope work 
-Connect with developers/dev shops
-Helping with onboarding process
-Snowballs

## What t-shirt size is this?
- [ ] x-large 
- [ ] large 
- [X ] medium
- [ ] small 
- [ ] x-small 

## What priority is this?
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [X ] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by thisisjoshford** [comment]
Is this proposal for developer outreach to create NFT projects on NEAR? If so, 100% on board with this plan :) Maybe you could you could clarify a little in the description?

**Comment by cjd425** [comment]
P1 
M
