### ISSUE TITLE
[DOCS] Add rainbow bridge documentation to docs

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#67]
# Proposal for: [add rainbow bridge documentation to docs]

## What is this? 
- Rainbow bridge is now on live on mainnet! 🌈 🎉 Let's get some documentation added to the NEAR <> ETH section of docs.

## Who needs to be involved?
- @thisisjoshford 

## Tasks to complete
- [ ] - incorporate [`rainbow-bridge-client`](https://github.com/near/rainbow-bridge-client/tree/main/packages/client) docs
- [ ] - incorporate [`rainbow-bridge-frontend`](https://github.com/near/rainbow-bridge-frontend) docs
- [ ] - incorporate [testing documentation](https://github.com/djsatok/bridge-testing)

## What t-shirt size is this?
MED

## What priority is this?
P1

**Comment by chadlamon** [comment]
I agree josh! With all the hype we give rainbow bridge on social, we need to do the application & users justice with getting some documentation added :D Great idea
