### ISSUE TITLE
[TASK] create `gasBurnt` arg for `near-api-js` & `near-cli`

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#70]
# Proposal for: [creating `gasBurnt` arg for `near-api-js` & `near-cli`]

## What is this? 
- Currently there is not a way to determine gas burnt for various methods used without viewing NEAR Explorer or using simulation testing.
- Information regarding `gas_burnt` and `tokens_burnt` are available but needs multiple receipts combined and total value returned
- would help fix near/docs/issues/626

## Who needs to be involved?
- @thisisjoshford 

## Tasks to complete
- [ ] write logic for adding `gas_burnt` for multiple receipts [see here](https://github.com/near-examples/collection-examples-rs/blob/main/getData.js#L20-L36) for work already completed in example app
- [ ] add to `near-cli`
- [ ] add to `near-api-js`

**Comment by mikedotexe** [comment]
Similar to https://github.com/near/near-cli/issues/412
If this gets accomplished in this ticket and it solves for that issue, let's make sure we close it
