### ISSUE TITLE
[TASK] Update contract testing docs

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#71]
# Proposal for: [update contract testing docs]

## What is this? 
- `near-sdk-sim` has finally been released for `near-skd-rs` and _can_ be used to test any `.wasm` file (ie. AS contracts).
- Detailed walkthrough of how to perform this should be created
- Existing testing documentation needs reviewal and enhancement (unit tests, end-to-end tests)
- see DOCS [issue #638](https://github.com/near/docs/issues/638)

## Who needs to be involved?
- @thisisjoshford 

## Tasks to complete
- [ ] review / revise / rewrite [testing rust contracts](https://docs.near.org/docs/develop/contracts/rust/testing-rust-contracts)
- [ ] review / revise / rewrite [testing as contracts](https://docs.near.org/docs/develop/contracts/as/testing-as-contracts)
- [ ] test newly released simulation testing library `near-sdk-sim`
- [ ] modify sim test to accept any .wasm file and create tutorial outlining the process

## What t-shirt size is this?
MED

## What priority is this?
P2
