### ISSUE TITLE
[EPIC] NEAR API server

### ISSUE THREAD

**Issue by zavodil** [near/devrel#73]
# Proposal for: 
Build new developer experience for web2 developers with NEAR API server

## What is this? 
- we created an [NFT server](https://github.com/zavodil/near-api-server) for a specific customer  and we can generalize it and make a production ready solution for every web2 developer 

## Who needs to be involved?
- Josh, Dorian, Chad, Matt

## Tasks to complete
- [ ] specify most wanted commands and implement their support
- [ ] simplify installation process (auto deploy nft/ft contract)
- [ ] implement generic call commands
- [ ] write documentation
- [ ] create a mind-blowing example (game on unity? meme generator to mint nft on a paras?)
- [ ] find potential developers, ask them to use api server and collect feedback
- [ ] publish a video with the whole process / article with code samples

## What t-shirt size is this?
- [ ] x-large 
- [x] large 
- [ ] medium
- [ ] small 
- [ ] x-small 

## What priority is this?
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [x] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by thisisjoshford** [comment]
Love the NFT server you created and certainly think creating a traditional RESTful API server that web2 devs are more accustomed to would be awesome. :)

**Comment by zavodil** [comment]
Generic call method [introduced](https://github.com/zavodil/near-api-server/commit/955d427a08d678ed13d98c70e16617d0c7565ec3) (Login required)

![Clip2net_210324231132](https://user-images.githubusercontent.com/38926321/112384918-a51ec500-8cf7-11eb-914d-aaa59de7c9cc.png)

**Comment by zavodil** [comment]
upgraded checkers board game into nft dapp in 33 lines of code https://github.com/codethejason/checkers/compare/master...zavodil:dApp?expand=1

**Comment by zavodil** [comment]
video with 2 NEAR API examples created and published https://twitter.com/zavodil_ru/status/1375187704451829762

**Comment by zavodil** [comment]
@joshuajbouw do you have capacity to help with the documentation? I wrote [draft version](https://github.com/zavodil/near-api-server) myself but need your guidance now

**Comment by zavodil** [comment]
Auto NFT contract deploy/init [added](https://github.com/zavodil/near-api-server/commit/5ea63a3ce9b55585c1f2065e68b1022aab827233)
