### ISSUE TITLE
[EPIC] Rainbow Bridge support

### ISSUE THREAD

**Issue by zavodil** [near/devrel#74]
# Proposal for: 
Find great Rainbow bridge use cases and promote them for all developers

## What is this? 
- Rainbow Bridge launched, project is huge and we have to multiply it impact for dev ecosystem

## Who needs to be involved?
- Vadim, Dorian, Matt, Josh, Mally, Dani

## Tasks to complete
- [x] Find the best channels to share bridge related content for Ethereum community
- [x] Collect stats on [Ethereum](https://duneanalytics.com/zavodil/rainbow-bridge) and Near side
- [x] Understand bridge benefits and the best ways to show them
- [x] Create example app(s) and use bridged tokens. 

## What t-shirt size is this?
- [ ] x-large 
- [X] large 
- [ ] medium
- [ ] small 
- [ ] x-small 

## What priority is this?
- [ ] P0 (EMERGENCY: drop everything to put out the fire)
- [X] P1 (Critical: docs, bugs, or features that block work or dev/app success)
- [ ] P2 (Important: known docs, feature requests, or known bugs)
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by thisisjoshford** [comment]
awesome! Certainly agree we should build example apps using the bridge and showcase functionality. :)

**Comment by cjd425** [comment]
P1
