### ISSUE TITLE
[EPIC] Onboarding Twitch Streamers & A Twitch Bot (?)

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#83]
# Proposal for: Give Twitch Streamers a way on Twitch to onboard their communities to NEAR.

## What is this? 
-  After working with the Human Guild, I got approval from them to send Twitch streamers interested in onboarding other members of their community to apply at their sputnik dao address for grants to onboard their community members to NEAR.
- I can manage all of the influencer relationships, but I need some sort of app or twitch bot they can use on stream to demo to their viewers with. I will need assistance here. I know @waverlymaven had some ideas, and maybe @zavodil will too?

Further Context: The twitch twitter community is blowing up in opposition over NFTS and crypto right now. This is a topic on everyone mind--we should use this as an opportunity.

## Who needs to be involved?
- Myself
- An engineer (could be a project for blockheads with @doriancrutcher or a @zavodil project)
- Documentation help for the streamers to use the final product. (cc: @thisisjoshford )

## Tasks to complete (can return to [x] these)

 - [x]  meet with streamers and onboard them to NEAR
 - [x] ask about the process and gather feedback, what do they think about NEAR, could they onboard their fans?
 - [x] discuss concepts from the crypto ecosystem: social tokens, DAOs, NFTs, level set their education
 - [x] ask what kind of tool would help them onboard their audience
- [x]  If bought in, direct them to apply at Sputnik Yolo Dao (Human Guild) for a grant

(later to do, or if have time)
- [ ]  Enhance exploringnear.com so that when people get NEAR they know how to interact with it
- [ ] Work with @zavodil on some sort of NEAR tip twitch bot & work with the creators of NEAR pixel-party on their idea for a community contest NFT dapp
- [ ] Provide the streamers with this tool and easy documentation on how to get it set up

## What t-shirt size is this? (range: multi-sprint to 1 hour)
Large

## What priority is this? (remove what doesn't apply)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by mattlockyer** [comment]
Not sure about the tasks... It seems like you have a few competing overall goals in the list of tasks.

One goal seems to be, show twitch streamers how to onboard people to NEAR.
Another goal seems to be, build something EVEN cooler to help twitch streamers onboard people to NEAR.

I think pick one for this epic and do it well, see if there's an expansion.

So one way is focus on the User Experience study part of this.

- [ ] meet with streamers and onboard them to NEAR
- [ ] ask about the process and gather feedback, what do they think about NEAR, could they onboard their fans?
- [ ] discuss concepts from the crypto ecosystem: social tokens, DAOs, NFTs, level set their education
- [ ] ask what kind of tool would help them onboard their audience

End of EPIC - We now have requirements for a tool, or tool(s) to build for Twitch Streamers :rocket:

**Comment by doriancrutcher** [comment]
So is this more for like a general thing where we partner with twitch streamers to have them showcase the apps we make? Am I understanding that correctly? If so I think it could be cool.

**Comment by zavodil** [comment]
I sent a request to [donationalerts](https://www.donationalerts.com/) to introduce NEAR payment method for their twitch donations. I guess this kind of integration will help to simply attract all streamers and their users... do we have an example of the integration offer?

**Comment by crasskitty** [comment]
> Not sure about the tasks... It seems like you have a few competing overall goals in the list of tasks.
> 
> One goal seems to be, show twitch streamers how to onboard people to NEAR.
> Another goal seems to be, build something EVEN cooler to help twitch streamers onboard people to NEAR.
> 
> I think pick one for this epic and do it well, see if there's an expansion.
> 
> So one way is focus on the User Experience study part of this.
> 
> * [ ]  meet with streamers and onboard them to NEAR
> * [ ]  ask about the process and gather feedback, what do they think about NEAR, could they onboard their fans?
> * [ ]  discuss concepts from the crypto ecosystem: social tokens, DAOs, NFTs, level set their education
> * [ ]  ask what kind of tool would help them onboard their audience
> 
> End of EPIC - We now have requirements for a tool, or tool(s) to build for Twitch Streamers 🚀

Precisely Matt, you did this so well.
Thanks for the help!

**Comment by crasskitty** [comment]
> I sent a request to [donationalerts](https://www.donationalerts.com/) to introduce NEAR payment method for their twitch donations. I guess this kind of integration will help to simply attract all streamers and their users... do we have an example of the integration offer?

Thank you @zavodil !! We do not have an example at this time, I'd love to sync with you either async or synchronously to determine what we could do here?

**Comment by crasskitty** [comment]
> So is this more for like a general thing where we partner with twitch streamers to have them showcase the apps we make? Am I understanding that correctly? If so I think it could be cool.

@doriancrutcher the idea is to onboard twitch streamers who then want to onboard their community and eventually have a few cool ways to do so!

**Comment by crasskitty** [comment]
UPDATE:

Solved by using a community member dapp building who built near-pixelparty.com. They will be building an app for communities to use on stream.
Also interviewed  and onboarded 7 streamers this past week. :) Will do more once this app is launched in 7-8 weeks.

**Comment by zavodil** [comment]
I just realized we have another approach of sending tips using my Near Auth tool. https://github.com/zavodil/near-auth
As soon as we will proof a connection between Near account and Twitch / Youtube / whatever account we will be able to send direct tips without 3rd party services

**Comment by crasskitty** [comment]
@zavodil this is AMAZING news :)
