### ISSUE TITLE
[TASK] Update exploringnear.com

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#84]
# Proposal for: Adding key features and other apps to exploringnear.com

## What is this? 
Exploringnear.com is an easy website for onboarding people new to crypto or new to NEAR onto the NEAR ecosystem of apps.

## Who needs to be involved?
- Myself
-  ANyone who wants to contribute!

## Tasks to complete (can return to [x] these)
- [x] Add a link to the near discord
- [x] Add a section for why this should matter to the average person
- [x] Consider adding different paths for artists/creators, financial people, ect.

## What t-shirt size is this? (range: multi-sprint to 1 hour)
Small

## What priority is this? (remove what doesn't apply)

- P3 (Nice-to-have: docs or features that improve a flow)
