### ISSUE TITLE
[EPIC] Demo Day

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#87]
# Proposal for:  Create Demo Day

## What is this? 
- An EPIC for the next sprint
- Currently: Only need to sync with Yadira

## Who needs to be involved?
-Dani, Gus, Yadira, AshC, Peter, and Max :) 

## Tasks to complete (can return to [x] these)
- [ ] Determine the day of demo day @waverlymaven & Yadira
- [ ] work on branding and asset collection @waverlymaven & @crasskitty 
- [ ] set up live production scenes with @crasskitty 
- [ ] copy those for prerecorded scenes with @chadlamon 
- [ ] more tbd

## What t-shirt size is this? (range: multi-spint to 1 hour)
L

## What priority is this? (remove what doesn't apply)
- P0 (EMERGENCY: drop everything to put out the fire)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
- P2 (Important: known docs, feature requests, or known bugs)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by crasskitty** [comment]
Is this different than the OWC demo day @waverlymaven ?

**Comment by chadlamon** [comment]
Let me know how I can help when this comes up! :)
