### ISSUE TITLE
Update / Enhance Docs for ETH Denver

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#9]
**WIP Preview:** https://docs-pr-602.onrender.com/

**TODO:**
(Feel free to add your own TODOs 🙂 )
- [x] add near-api-js cheat sheet @mattlockyer 
- [x] add[ near-api-js overview](https://docs-pr-602.onrender.com/docs/develop/front-end/near-api-js) @mattlockyer 
- [x] enhance / revise [frontend overview](https://docs-pr-602.onrender.com/docs/develop/front-end/introduction) @mattlockyer 
- [x] enhance / revise [contract overview](https://docs-pr-602.onrender.com/docs/develop/contracts/overview) @mattlockyer 
- [x] [`new-to-near`](https://docs-pr-602.onrender.com/docs/concepts/new-to-near) copy revisions @nearlyalmonds 
- [ ] [`new-to-near`](https://docs-pr-602.onrender.com/docs/concepts/new-to-near) project links (awesomenear, berryclub, paras, etc.) @thisisjoshford 
- [x] [community channels / faq](https://docs-pr-602.onrender.com/docs/community/community-channels) @jlwaugh 
- [x] [near.dev](https://near.dev) examples audit @doriancrutcher 
- [x] match `near-explorer.md` with NEW `near-wallet.md` @thisisjoshford 
- [x] re-org tutorials section @thisisjoshford 
- [x] add NEAR 101 & NEAR 102 to develop landing page @thisisjoshford 
- [x] add Sherif's workshop repos to tutorials @thisisjoshford 
- [x] add live application review @thisisjoshford 
- [x] check and fix all broken links from re-org @thisisjoshford 
- [x] bounties page under community @jlwaugh 
- [x] fix [near.dev](https://near.dev) examples based on @doriancrutcher findings @mattlockyer 
- [x] add hackathon startup guide @thisisjoshford 
- [x] add tutorials overview @thisisjoshford 
- [x] add local net creation section
- [ ] update NEAR 101 & 102 slides (video link & enhance visibility) @thisisjoshford 
- [x] update Hackathon Getting Started Guide @nearlyalmonds 
---

**After Merge:**
- [ ] redirect old pages to new docs via Render
- [ ] comb NEAR repos for links & fix (Wallet / Explorer P0)

---

**Stretch Goals:**
- [x] add live application review descriptions @mattlockyer / @jlwaugh 
- [ ] update [near-sdk-as overview / guide](https://docs-pr-602.onrender.com/docs/develop/contracts/as/as-intro)
- [ ] update [near-sdk-rs overview / guide](https://docs-pr-602.onrender.com/docs/develop/contracts/rust/rust-intro)
- [ ] add info about [NEAR Wallet doc](https://docs-pr-602.onrender.com/docs/tools/near-wallet) (2 - 3 sentences) @nearlyalmonds 
- [x] add info about [NEAR Explorer doc](https://docs-pr-602.onrender.com/docs/tools/near-explorer) (2 - 3 sentences) @thisisjoshfordd
- [ ] add high level account description in [/concepts/account](https://docs-pr-602.onrender.com/docs/concepts/account) @nearlyalmonds

**Comment by mattlockyer** [comment]
Matt's TODOs
- [ ] Add near-api-js cheat sheet @mattlockyer 
- [ ]
