### ISSUE TITLE
[TASK] Robert - Partners

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#90]
# Proposal for: Help integrate NEAR with partner projects

## What is this? 
- Work with partners and integrate NEAR into their projects

## Who needs to be involved?
- 

## Tasks to complete (can return to [x] these)
- [x] Partner X: resume the development of connector and indexer
- [ ] Partner X: deploy a testing version with frontend and backend (delayed since partner's developer didn't get sufficient time)
- [x] Partner Y: pending on the request of the partner (no actual request received)
- [x] Partner Z: provide support for NFT

## What t-shirt size is this? (range: multi-sprint to 1 hour)
medium (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
