### ISSUE TITLE
[TASK] Stake Drop

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#91]
# Proposal for: implement the "stake drop" feature, and create the "stake drop" analytics dashboard

## What is this? 
- More about the Airdrop improvement could be found in https://gov.near.org

## Who needs to be involved?
- Stefano
- Tiffany
- Yifang

## Tasks to complete (can return to [x] these)
- [ ] wallet: confirm the design with Stefano: https://github.com/near/near-wallet-roadmap/issues/23
- [X] wallet: set up the timeline of development with community 
- [ ] wallet: work on the wallet bounty with community developer (Y Zhu): https://github.com/near/bounties/issues/51
- [ ] bot: send rewards if user stake certain amount of NEAR within X days
- [X] analytics: define the airdrop journey dashboard with Tiffany and Yifang
- [ ] analytics: improve the analytics based on the latest wallet design

## What t-shirt size is this? (range: multi-spint to 1 hour)
small (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
