### ISSUE TITLE
[TASK] Add Chinese version for Docs

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#92]
# Proposal for: deploy Chinese version of docs.near.org into production

## What is this? 
- We have been working on the translation of docs into Chinese as described here: https://gov.near.org/t/i18n-support-for-https-docs-near-org/598
- We are almost done with proof reading, and will add the Chinese version into production
- The Chinese version of the docs will remove roadblocks for many Chinese developers to start with NEAR

## Who needs to be involved?
- Josh (for help review the design and PR)

## Tasks to complete (can return to [x] these)
- [ ] Complete the Proof Reading of the **Concepts** section 
- [ ] Fix severals issues of the i18n version of the docs site (will add more details about the issues later)
- [ ] Submit PR, review the route change issue and PR with Josh
- [ ] Merge the PR and deploy the i18n-enabled docs site 

## What t-shirt size is this? (range: multi-spint to 1 hour)
small (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
