### ISSUE TITLE
[TASK] NEAR Certified Developer (NCD) for Chinese developers

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#93]
# Proposal for: NEAR Certified Developer (NCD) for Chinese developers

## What is this? 
- the Chinese version of NCD, including bi-weekly courses and L1v interview, and community mentorship programs, etc.

## Who needs to be involved?
- Sherif

## Tasks to complete (can return to [x] these)
- [X] kick off the NCD CN plan with Sherif
- [ ] help host cohort 6 in May 3rd - 7th
- [ ] L1v interviews for Chinese developers
- [ ] build the mentors team
- [ ] organize and improve the Chinese docs and materials
- [ ] plan the Chinese NCD agenda, meeting time, process, etc. 

## What t-shirt size is this? (range: multi-spint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
