### ISSUE TITLE
[TASK] NEAR Certified Developer Program: Cohort 3

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#94]
# Proposal for: help support NCD Cohort 3 in CN community 

## What is this? 
- Provide support to Chinese developer community, and also help with Sherif and Sasha

## Who needs to be involved?
- Sherif
- Sasha

## Tasks to complete (can return to [x] these)
- [x] help organize the event for Sherif and Sasha
- [x] Q/A for developers in Chinese community for course and demo project
- [x] collect feedback and improve NCD

## What t-shirt size is this? (range: multi-spint to 1 hour)
small (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
