### ISSUE TITLE
[TASK] NEAR Technical Posts Proof Reading

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#95]
# Proposal for: help with proof reading posts translated from English to Chinese

## What is this? 
- Help proof read docs that are translated into Chinese by Homer

## Who needs to be involved?
- Homer

## Tasks to complete (can return to [x] these)
- [X] Proof Reading: Engineering update, Mar 19th & 26th
- [X] Proof Reading: Rainbow Bridge release
- [X] Proof Reading: EVM update

## What t-shirt size is this? (range: multi-spint to 1 hour)
x-small (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)
