### ISSUE TITLE
[EPIC] One-Button Click NFT Creation with NEAR + Hive / Steem

### ISSUE THREAD

**Issue by think-in-universe** [near/devrel#97]
# Proposal for: make it possible to create NFT on Hive / Steem by integrating with NEAR

## What is this? 
- make it possible to create NFT by one-button click on Hive / Steem frontend, by integrating with NEAR

### ideas

there're some interesting part of the integration: 

1. both STEEM (HIVE) and NEAR used a named account, we could some kind of mapping from STEEM account to NEAR account
2. STEEM or HIVE both have a lot of content creators there and could find some fit with NFT; 
3. STEEM (HIVE) and NEAR both some good web 2 like experience, and some shared design principles I think; 
4. If built right, maybe the STEEM (HIVE) users can run smart contract with their STEEM/HIVE keys (the STEEM/HIVE community is always eager to have some smart contract layer integrated with their network).

### design

use NEAR + Steem as an example. it would be the same for Hive. 

1. create NEAR account from Steem account in a daemon
    1. create NEAR account with Steem's public key
        1. [ ] challenge: can we use Steem’s public key to map to Near account
    2. call create account function
        1. [ ] add a custom_json method create-near-account
        2. [ ] pay Steem fees for NEAR account creation via a gateway
        3. [ ] call `near-api-js` createAccount with Steem’s public key + Steem’s username
2. call NFT contract on NEAR
    1. method 1: using posting key
        1. [ ] call NFT contract method with `near-api-js` with account’s private key
    2. method 2: using Steem Keychain
        1. [ ] in the DApp, using Steem Keychain, call NFT contract method with near-api-js to create the NFT proof for that post
        2. [ ] may need to change Steem Keychain to make it possible to call a NEAR contract method
3. challenge
    1. signature algorithm: ed25519 v.s. seck256k1

## Who needs to be involved?
- Matt
- Vadim

## Tasks to complete (can return to [x] these)
- [ ] confirm the value, design and plan of the project 
- [ ] share the design with Steem / Hive community and call for contribution from communities
- [ ] implement a NFT demo with NEAR + Steem / Hive

## What t-shirt size is this? (range: multi-spint to 1 hour)
x-large (x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by cameron-NEAR** [comment]
I love this idea and would be happy to make it a bounty if you think the community can build it

**Comment by think-in-universe** [comment]
@cameron-NEAR thanks Cameron. yeah. definitely we want to work with Hive / Steem community to build it. I already got contacted with a few developers and will invite for contribution once I finalize the initial design. 

I was thinking about applying for grant to motivate developers to work on it, but should be also OK to publish bounties for specific features.
