### ISSUE TITLE
[EPIC] Matt Partners

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#99]
- [x] Abridged gather reqs for integration
- [x] Draw lines with partners
- [x] EPAM / MintGate Kickoff
- [x] YR call
